### ISSUE TITLE
If too many checkins are scheduled PolicyLengthExceededException occurs

### ISSUE THREAD

**Issue by aaron-pham** [sw-tools/checkin-service#7]
I noticed this bug when testing my frontend with my flights. It appears that Lambda functions have a max policy length and if there are too many checkins schedule (therefore, many permissions on the `HandleScheduledCheckin`), we will get `PolicyLengthExceededException` and weird behavior occurs.

Not really sure how we'd fix this, as this may be a limitation with the lambda functions. Also, since I assume this checkin service is mainly for personal use, this issue is unlikely to occur.

Here's a stack trace from my lambda logs. 
```
2022-02-06T23:17:34.025Z	a2b7e2c6-c73f-4501-be64-2d7fc4e101a3	ERROR	PolicyLengthExceededException: The final policy size (20719) is bigger than the limit (20480).
    at deserializeAws_restJson1AddPermissionCommandError (/var/task/node_modules/@aws-sdk/client-lambda/dist-cjs/protocols/Aws_restJson1.js:2235:41)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /var/task/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:6:20
    at async /var/task/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:11:20
    at async StandardRetryStrategy.retry (/var/task/node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js:51:46)
    at async /var/task/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:6:22
    at async handleInternal (/var/task/src/handlers/schedule-checkin.js:107:9)
    at async Runtime.handle [as handler] (/var/task/src/handlers/schedule-checkin.js:47:18) {
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 400,
    requestId: '239d16c5-7b35-4abe-8486-44a13d7c64cb',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  Type: 'User'
}

**Comment by swtools0** [comment]
Hi @aaron-pham, thanks for reporting this!

Is this an issue with having too many active future flights, or an issue with having too many past flights?

If it's an issue with too many active future flights, we probably need to look into alternatives to adding permissions directly the the Lambda function. Maybe we need to create a role to attach to the function or something along those lines.

If it's just an issue with having had too many past flights, we can probably delete the old permissions after a user has been checked in.

**Comment by mattddean** [comment]
@aaron-pham thoughts? https://github.com/sw-tools/checkin-service/pull/9

**Comment by aaron-pham** [comment]
Looked at the PR and wrote comments there! I like it!
